[phases.setup]
nixPkgs = ["python311", "ffmpeg", "opus", "nodejs"]

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python control_panel.py"
